package com.bankApplication.exponent.autoGenerator;

public class AccountNoAutoGenerator {
	public static long generateAccountNo() {
		double num = Math.random();
		long autogeneratedAccNo = (long) (Math.random() * (Math.pow(10, 13)));
		return autogeneratedAccNo;
	}
}
